### ISSUE TITLE
Protocol "sftp" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by jzadra** [stenevang/sftp#12]
Trying to upload with `sftp_upload()`.

Get the error:
``` 
 Error in function (type, msg, asError = TRUE)  : 
     Protocol "sftp" not supported or disabled in libcurl
```

System: OSX 12.1 (Monterey)
R: 4.1.2
sftp: 2.0.10
curl: 4.3.2

**Comment by stenevang** [comment]
The error you see is caused by how libcurl was built and installed on the operating system you have. For example, see this: https://stackoverflow.com/questions/13171550/sftp-support-for-curl-on-osx
(my R-package sftp uses another R-package RCurl which is an implementation for R of curl (https://curl.se/) which means RCurl has a dependency on libcurl).
